//
// Created by Sony on 26.05.2018.
//

#ifndef OBS_STUDIO_MATCHCONNECTIONGLOBAL_H
#define OBS_STUDIO_MATCHCONNECTIONGLOBAL_H

#ifdef MATCH_CONN_EXPORT
#define MATCH_CONN_DECL_EXPORT Q_DECL_EXPORT
#else
#define MATCH_CONN_DECL_EXPORT Q_DECL_IMPORT
#endif

#endif //OBS_STUDIO_MATCHCONNECTIONGLOBAL_H
